- hosts: localhost
  tasks:
    - name: Install Git
      become: yes
      package:
        name: git
        state: present

    - name: Enable Night Light
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: true

    - name: Set Night Light Temperature
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: uint32 5500

    - name: Enable Flathub repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Fractal
      become: yes
      command: flatpak install --assumeyes flathub org.gnome.Fractal

    - name: Install Spotify
      become: yes
      command: flatpak install --assumeyes flathub com.spotify.Client

    - name: sshd configuration file update
        template: src=/etc/ansible/configs/etc/ssh/sshd_config.j2
          dest=/etc/ssh/sshd_config
          backup=yes
          owner=0 group=0 mode=0644
          validate='/usr/sbin/sshd -T -f %s'
    notify:
    - restart sshd

    handlers:
      - name: restart sshd
          service: name=sshd state=restarted
